const express = require('express')
const router = express.Router()
const authController = require("../controllers/Auth")
const { verifyToken } = require('../middleware/VerifyToken')
const { loginValidation } = require('../validators/authValidator')
const validate = require('../middleware/validateRequest')
const { getAllServiceProvider, getAllServiceCategories } = require('../controllers/search-and-select/searchSelect.controller')
const { logoutActivity, profileUpdatedActivity } = require('../middleware/activity')

router
    .post("/signup", authController.signup)
    .patch("/:id", verifyToken, profileUpdatedActivity, authController.updateUser)
    .get("/profile/:id", authController.getUserProfile)
    .get("/users/:role", authController.getOrganizer)
    .post('/login', validate(loginValidation), authController.login)
    .post("/verify-otp", authController.verifyOtp)
    .post("/resend-otp", authController.resendOtp)
    .post("/forgot-password", authController.forgotPassword)
    .post("/reset-password", authController.resetPassword)
    .get("/check-auth", verifyToken, authController.checkAuth)
    .post('/logout', verifyToken, logoutActivity, authController.logout)
    .get('/providers', verifyToken, getAllServiceProvider)
    .get('/providers/service', getAllServiceCategories)
    .put('/cover', verifyToken, authController.updateCover)
    .put('/avatar', verifyToken, authController.updateAvatar)
    .post("/reviews", verifyToken, authController.createReview)
    .put("/reviews/:reviewId/reply", verifyToken, authController.addReply)
    .get("/reviews",verifyToken, authController.getProviderReviews);

module.exports = router